(import swl:module-setup)
;; Run the existing assignment without changing its source files.
(current-directory (getenv "SWL_AI1_DIR"))
(random-seed 42)
(define algorithm (getenv "SWL_AI1_ALGORITHM"))
(with-input-from-file "grid-main.ss"
  (lambda ()
    (let loop ([form (read)])
      (unless (eof-object? form)
        (eval (if (and (pair? form) (eq? (car form) 'load)
                       (member (cadr form) '("grid-BFS.ss" "grid-DFS.ss" "grid-BEST.ss")))
                  `(load ,(string-append "grid-" algorithm ".ss"))
                  form))
        (loop (read))))))
(define result-path (get-path goal))
(unless (and (equal? (car result-path) goal)
             (equal? (car (reverse result-path)) start))
  (error 'verify "search did not connect start and goal"))
(let loop ([path result-path])
  (unless (null? (cdr path))
    (let ([a (car path)] [b (cadr path)])
      (unless (= (+ (abs (- (car a) (car b))) (abs (- (cadr a) (cadr b)))) 1)
        (error 'verify "path contains a nonadjacent step")))
    (loop (cdr path))))
(import swl:threads)
(thread-fork
  (lambda ()
    (thread-sleep 500)
    (with-output-to-file (string-append (getenv "SWL_VERIFY_DIR") "/success.txt")
      (lambda () (printf "ARM64_AI1_~a_OK path-nodes=~a\n" algorithm (length result-path)))
      'replace)
    ((foreign-procedure "_exit" (int) void) 0)))
